[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  DATABASE_URL = "postgresql://postgres.fxvalblrnbwosabyjnxe:%40Mabarvip0987@aws-0-ap-northeast-1.pooler.supabase.com:6543/postgres?pgbouncer=true"
  DIRECT_URL = "postgresql://postgres.fxvalblrnbwosabyjnxe:%40Mabarvip0987@aws-0-ap-northeast-1.pooler.supabase.com:5432/postgres"
  NEXTAUTH_SECRET = "aDT70VYq0FJGft1BegVgtgtrYvHVnzLd93PkqACvM8s="
  NEXTAUTH_URL = "https://microboy.com"
  ADMIN_USERNAME = "admin_virtus"
  ADMIN_PASSWORD = "@Deathready0"
  NEXT_PUBLIC_SUPABASE_URL = "https://fxvalblrnbwosabyjnxe.supabase.co"
  NEXT_PUBLIC_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ4dmFsYmxybmJ3b3NhYnlqbnhlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3OTAxNjUxMTIsImV4cCI6MjEwNTc0MTExMn0.YMmQvtMYqpwjPRQdWvPkCUEfezFXppEDxjZctZ7qbG4"
  SUPABASE_SERVICE_ROLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ4dmFsYmxybmJ3b3NhYnlqbnhlIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc5MDE2NTExMiwiZXhwIjoyMTA1NzQxMTEyfQ.vjPIRrcRONabBff6jRvSlS6rbFKKWvfaAG1i5Gg1l4M"

[[plugins]]
  package = "@netlify/plugin-nextjs"
